language: go

go:
  - 1.12.x

addons:
  chrome: stable

before_install:
  - export GO111MODULE=on

install:
  - go get github.com/agnivade/wasmbrowsertest

script:
  # Diff Go format.
  - diff -u <(echo -n) <(gofmt -d .)
  # Run Go tests.
  - GOOS=js GOARCH=wasm go test -v -exec="$GOPATH/bin/wasmbrowsertest"
