name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install wasmbrowsertest
        run: go install github.com/agnivade/wasmbrowsertest@latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        env:
          GOOS: js
          GOARCH: wasm
        run: go test -exec="$(go env GOPATH)/bin/wasmbrowsertest"
